name: Install & test PHP code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      version: '5.6'
      extensions: mongo, redis
      SYMFONY_ENV: test
      APP_ENV: test
    steps:

      - name: Setup PHP environment
        uses: shivammathur/setup-php@verbose
        with:
          php-version: ${{ env.version }}
          extensions: ${{ env.extensions }}

      - name: Check out code
        uses: actions/checkout@v2
